### ISSUE TITLE
What is .prop() function doing?

### ISSUE THREAD

**Issue by andrewmcampgit** [PercyODI/Stage2.PieAuction#14]
File: PieAuction.FrontEnd/pie_page/pie_page.js
LineNumber: 51

In pie_page.js, line 51 is calling a function .prop()  on object pie.ImageAddress. I don't remember seeing this before?

**Comment by alyraptor** [comment]
@andrewmcampgit

```
// Render the image
$("#pie-image").prop("src", pie.ImageAddress);
```
The comment does a decent job of describing what this line does, BUT for more information, this would be a great example of when to use the [jQuery Documentation](https://api.jquery.com/)!

**Comment by andrewmcampgit** [comment]
fhdrth
