### ISSUE TITLE
What is the purpose of time left and start time?

### ISSUE THREAD

**Issue by leighmaj** [PercyODI/Stage2.PieAuction#18]
pie_page.js line 65 to 68
I am not sure the purpose of this within the app?

**Comment by PercyODI** [comment]
There is a timer on the Pie Page, stating how long is left on an auction.

![image](https://user-images.githubusercontent.com/9019296/73100604-79b20780-3eb3-11ea-993e-90192df1e5b9.png)

**Comment by leighmaj** [comment]
I see this now.
