### ISSUE TITLE
What is happening here? Property Rendering?

### ISSUE THREAD

**Issue by andrewmcampgit** [PercyODI/Stage2.PieAuction#20]
File: PieAuction.FrontEnd/PiePage.js
LineNumber: 39-48

Are we appending items to the HTML to show up on the page visually?

also add class? same thing?

**Comment by PercyODI** [comment]
Pie properties are put in the boxes under the pie name on the pie page. See Image; the properties on this pie are "Blueberry" and "Vegan".

![image](https://user-images.githubusercontent.com/9019296/73100981-589de680-3eb4-11ea-8e57-d50d786a9015.png)
